[project]
name = 'DCIP'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ai-integration]
path = 'contracts/ai-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.challenge-manager]
path = 'contracts/challenge-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.idea-nft]
path = 'contracts/idea-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.solution-submission]
path = 'contracts/solution-submission.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
